server.port: 8082
spring:
  datasource:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://localhost:5432/clinic"
#    name: "lowCrm"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true


#spring.jpa.generate-ddl=true
#server.error.include-message=always
bot:
  name: low_crm_bot
  token:  5429696420:AAGPCjOa6txDWXaNUgW3UBcBnVgKyZ39gvE
dadata:
  client:
    token: dc696ca87eeb9349b1023e265db470bedbe5f4f5

clinic:
  datasource:
    url: "jdbc:postgresql://92.241.100.3:58297/1Cdata"
    username: "1cdb00"
    password: "UN77v.DaMp9"
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
